name: CI
on:
  workflow_dispatch:

jobs:
  test-pipe-hang:
    name: docker-sfx-${{ matrix.image }}
    runs-on: windows-${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [2019, 2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        shell: cmd
        run: |
          curl -LO https://github.com/msys2/msys2-installer/releases/download/2022-03-19/msys2-base-x86_64-20220319.sfx.exe
          docker build -t msys2-base -f ./.ci/Dockerfile.${{ matrix.image }} .
      - name: Test without Login Shell
        run: |
          docker run msys2-base c:\windows\system32\whoami.exe /all
          docker run msys2-base C:\msys64\usr\bin\pacman.exe -Syy
          docker run msys2-base C:\msys64\usr\bin\pacman.exe --noconfirm -S vim
      - name: Test
        run: |
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman --version"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Qkv"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Syy"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm git"
